package scanner

// Shared command names and arguments keep the scanner catalog consistent.
const (
	binApk     = "apk"
	binApt     = "apt"
	binBrew    = "brew"
	binChoco   = "choco"
	binDocker  = "docker"
	binFlatpak = "flatpak"
	binGo      = "go"
	binMas     = "mas"
	binNpm     = "npm"
	binNvm     = "nvm"
	binPacman  = "pacman"
	binPipx    = "pipx"
	binRustup  = "rustup"
	binScoop   = "scoop"
	binSDKMAN  = "sdkman"
	binSnap    = "snap"
	binWinget  = "winget"
	binZypper  = "zypper"
	binYay     = "yay"
	binBun     = "bun"
	binPnpm    = "pnpm"
	binDnf     = "dnf"
	binCargo   = "cargo"
	binDu      = "du"

	cleanupIcon = "🧹"
	flagDuShort = "-sh"

	flagGlobal      = "-g"
	flagVersion     = "--version"
	scannerNL       = "\n"
	cmdInstall      = "install"
	cmdList         = "list"
	cmdUpdate       = "update"
	cmdUpgrade      = "upgrade"
	statusInstalled = "installed"
	versionDot      = "."

	binAntigravity = "antigravity"
	binClaude      = "claude"
	binCopilot     = "copilot"
	binCursor      = "cursor"
	binGemini      = "gemini"
	binGh          = "gh"
	binGrok        = "grok"
	binOpenCode    = "opencode"
	binPi          = "pi"
	binWindsurf    = "windsurf"
	binGcloud      = "gcloud"
	binSemidx      = "semidx"
)
