package retention

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// IsOlderThan reports whether modTime is older than maxDays relative to now.
// maxDays <= 0 means "never older" (retain everything).
func IsOlderThan(modTime time.Time, maxDays int, now time.Time) bool {
	if maxDays <= 0 {
		return false
	}
	cutoff := now.AddDate(0, 0, -maxDays)
	return modTime.Before(cutoff)
}

// DiskPressureTriggered reports whether used percent is at or above the threshold.
func DiskPressureTriggered(usedPct, threshold int) bool {
	if threshold <= 0 {
		return false
	}
	return usedPct >= threshold
}

// PathCandidate is a file/dir selected for age-based cleanup.
type PathCandidate struct {
	Path string
	Size int64
}

// CollectOldPaths walks root (max depth) and returns entries whose mtime is older
// than maxDays. Skips missing roots. Depth 0 means root itself only; depth 1
// means immediate children (typical for cache dirs).
func CollectOldPaths(root string, maxDays, maxDepth int, now time.Time) ([]PathCandidate, int64, error) {
	_, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, 0, nil
		}
		return nil, 0, err
	}
	if maxDepth <= 0 {
		return collectLeaf(root, maxDays, now)
	}

	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, 0, err
	}
	var out []PathCandidate
	var total int64
	for _, e := range entries {
		p := filepath.Join(root, e.Name())
		fi, err := e.Info()
		if err != nil {
			continue
		}
		sz := int64(0)
		if e.IsDir() {
			latest, err := latestPathMtime(p)
			if err != nil {
				return nil, 0, fmt.Errorf("inspect %s: %w", p, err)
			}
			if !IsOlderThan(latest, maxDays, now) {
				continue
			}
			sz = dirSize(p)
		} else {
			if !IsOlderThan(fi.ModTime(), maxDays, now) {
				continue
			}
			sz = fi.Size()
		}
		out = append(out, PathCandidate{Path: p, Size: sz})
		total += sz
	}
	return out, total, nil
}

func collectLeaf(root string, maxDays int, now time.Time) ([]PathCandidate, int64, error) {
	latest, err := latestPathMtime(root)
	if err != nil {
		return nil, 0, fmt.Errorf("inspect %s: %w", root, err)
	}
	if !IsOlderThan(latest, maxDays, now) {
		return nil, 0, nil
	}
	sz := dirSize(root)
	return []PathCandidate{{Path: root, Size: sz}}, sz, nil
}

// latestPathMtime returns the newest mtime in a path without following
// symlinked directories. A failure is returned instead of allowing a
// partially inspected tree to become a deletion candidate.
func latestPathMtime(root string) (time.Time, error) {
	info, err := os.Lstat(root)
	if err != nil {
		return time.Time{}, err
	}
	latest := info.ModTime()
	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == root {
			return nil
		}
		entryInfo, err := d.Info()
		if err != nil {
			return err
		}
		if entryInfo.ModTime().After(latest) {
			latest = entryInfo.ModTime()
		}
		return nil
	})
	if err != nil {
		return time.Time{}, err
	}
	return latest, nil
}

func dirSize(root string) int64 {
	var total int64
	// WalkDir is best effort: unreadable descendants are skipped while sizing.
	_ = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		fi, err := d.Info()
		if err != nil {
			return nil
		}
		total += fi.Size()
		return nil
	})
	return total
}

// RemovePaths deletes each path (file or directory). Returns freed bytes best-effort.
func RemovePaths(paths []string) (freed int64, errs []string) {
	for _, p := range paths {
		fi, err := os.Stat(p)
		if err != nil {
			errs = append(errs, p+": "+err.Error())
			continue
		}
		var sz int64
		if fi.IsDir() {
			sz = dirSize(p)
		} else {
			sz = fi.Size()
		}
		if err := os.RemoveAll(p); err != nil {
			errs = append(errs, p+": "+err.Error())
			continue
		}
		freed += sz
	}
	return freed, errs
}

// projectBuildDirNames are per-project build artifact directories that are
// always safe to reclaim (they are regenerated by the next build).
var projectBuildDirNames = map[string]struct{}{
	"target": {}, "build": {}, "dist": {}, ".next": {}, "out": {},
	".turbo": {}, ".pytest_cache": {}, "__pycache__": {},
}

// CollectProjectBuildPaths walks projectsDir (one project per first-level
// directory) and collects build artifact directories. Build dirs are always
// collected; node_modules only when the project shows no recent activity.
//
// Safety properties:
//   - ctx cancellation aborts the walk and is returned as the error;
//   - symlinks are never followed (WalkDir uses lstat) and symlinked project
//     entries are skipped;
//   - candidates are built from the canonicalized root and validated to stay
//     beneath it; the projectsDir itself is never collected;
//   - per-project walk/stat failures are accumulated in partialErrs (fail-safe:
//     a project whose recency cannot be determined keeps its node_modules)
//     instead of aborting the whole collection.
func CollectProjectBuildPaths(ctx context.Context, projectsDir string, maxDays int, now time.Time) ([]PathCandidate, int64, []string, error) {
	if err := ctx.Err(); err != nil {
		return nil, 0, nil, err
	}
	// Syntactic safety runs before any filesystem access so an unsafe root is
	// rejected even when it does not exist.
	abs, err := filepath.Abs(projectsDir)
	if err != nil {
		return nil, 0, nil, err
	}
	if err := checkProjectsRootSyntax(abs); err != nil {
		return nil, 0, nil, err
	}
	info, err := os.Stat(projectsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, 0, nil, nil
		}
		return nil, 0, nil, err
	}
	if !info.IsDir() {
		return nil, 0, nil, nil
	}
	root, err := canonicalRoot(projectsDir)
	if err != nil {
		return nil, 0, nil, err
	}
	if err := validateProjectsRoot(root); err != nil {
		return nil, 0, nil, err
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, 0, nil, err
	}

	var out []PathCandidate
	var total int64
	var partial []string
	for _, entry := range entries {
		if err := ctx.Err(); err != nil {
			return out, total, partial, err
		}
		// Skip symlinks (never follow out of the tree), non-dirs, dotfiles.
		if entry.Type()&fs.ModeSymlink != 0 || !entry.IsDir() || entry.Name()[0] == '.' {
			continue
		}
		cands, sz, errs, err := collectOneProject(ctx, root, entry.Name(), maxDays, now)
		partial = append(partial, errs...)
		if err != nil {
			return out, total, partial, err
		}
		out = append(out, cands...)
		total += sz
	}
	return out, total, partial, nil
}

// collectOneProject walks a single project directory. A non-nil error is
// returned only on context cancellation; walk/stat failures are reported in
// the partialErrs slice.
func collectOneProject(ctx context.Context, root, name string, maxDays int, now time.Time) ([]PathCandidate, int64, []string, error) {
	projPath := filepath.Join(root, name)
	var out []PathCandidate
	var total int64
	var partial []string

	projIsStale := projectStale(projPath, maxDays, now, &partial)

	walkErr := filepath.WalkDir(projPath, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			partial = append(partial, path+": "+err.Error())
			return nil
		}
		if cerr := ctx.Err(); cerr != nil {
			return cerr
		}
		if !d.IsDir() || path == projPath {
			return nil
		}
		switch dName := d.Name(); {
		case dName == ".git" || dName == ".svn":
			return filepath.SkipDir
		case dName == "node_modules" && !projIsStale:
			// Active project: keep node_modules and do not descend into it.
			return filepath.SkipDir
		case dName == "node_modules" || isProjectBuildDir(dName):
			return collectBuildDir(ctx, root, path, &out, &total, &partial)
		default:
			return nil
		}
	})
	if walkErr != nil {
		return out, total, partial, walkErr
	}
	return out, total, partial, nil
}

// collectBuildDir sizes and records one build directory, then stops the
// descent into it.
func collectBuildDir(ctx context.Context, root, path string, out *[]PathCandidate, total *int64, partial *[]string) error {
	if !strings.HasPrefix(path, root+string(os.PathSeparator)) {
		*partial = append(*partial, path+": escapes projects root")
		return filepath.SkipDir
	}
	sz, err := dirSizeCtx(ctx, path)
	if err != nil {
		return err
	}
	if sz > 0 {
		*out = append(*out, PathCandidate{Path: path, Size: sz})
		*total += sz
	}
	return filepath.SkipDir
}

// projectStale reports whether a project shows no activity newer than
// maxDays, using the newest mtime among the project dir and its first-level
// entries. When recency cannot be determined (unreadable project) it fails
// safe: the project is treated as active and a partial error is recorded.
func projectStale(projPath string, maxDays int, now time.Time, partial *[]string) bool {
	latest, err := latestProjectMtime(projPath, partial)
	if err != nil {
		*partial = append(*partial, projPath+": "+err.Error())
		return false
	}
	return IsOlderThan(latest, maxDays, now)
}

// latestProjectMtime returns the newest mtime among the project dir and its
// first-level entries. A failed Stat/ReadDir is a hard error (recency
// unknown); per-entry Info failures are recorded as partial errors and
// skipped.
func latestProjectMtime(projPath string, partial *[]string) (time.Time, error) {
	info, err := os.Stat(projPath)
	if err != nil {
		return time.Time{}, err
	}
	entries, err := os.ReadDir(projPath)
	if err != nil {
		return time.Time{}, err
	}
	latest := info.ModTime()
	for _, e := range entries {
		fi, err := e.Info()
		if err != nil {
			*partial = append(*partial, filepath.Join(projPath, e.Name())+": "+err.Error())
			continue
		}
		if fi.ModTime().After(latest) {
			latest = fi.ModTime()
		}
	}
	return latest, nil
}

// checkProjectsRootSyntax refuses the filesystem root and paths too shallow
// to be a dedicated projects folder.
func checkProjectsRootSyntax(root string) error {
	if filepath.Dir(root) == root {
		return fmt.Errorf("unsafe projects root %q: refusing filesystem root", root)
	}
	parts := strings.FieldsFunc(strings.TrimPrefix(root, filepath.VolumeName(root)),
		func(r rune) bool { return r == os.PathSeparator })
	if len(parts) < 2 {
		return fmt.Errorf("unsafe projects root %q: too shallow to be a dedicated projects directory", root)
	}
	return nil
}

// validateProjectsRoot refuses dangerous projects roots: the syntax checks
// plus the user's home directory. Fail-closed: CollectProjectBuildPaths
// returns the error and collects nothing.
func validateProjectsRoot(root string) error {
	if err := checkProjectsRootSyntax(root); err != nil {
		return err
	}
	if home, err := os.UserHomeDir(); err == nil && home != "" {
		if canonHome, err := canonicalRoot(home); err == nil && canonHome == root {
			return fmt.Errorf("unsafe projects root %q: refusing the user home directory", root)
		}
	}
	return nil
}

func isProjectBuildDir(name string) bool {
	_, ok := projectBuildDirNames[name]
	return ok
}

// canonicalRoot resolves root to an absolute, symlink-free path.
func canonicalRoot(root string) (string, error) {
	abs, err := filepath.Abs(root)
	if err != nil {
		return "", err
	}
	return filepath.EvalSymlinks(abs)
}

// dirSizeCtx is dirSize with context cancellation, for potentially huge
// build trees such as node_modules.
func dirSizeCtx(ctx context.Context, root string) (int64, error) {
	var total int64
	// WalkDir is best effort: unreadable descendants are skipped while sizing.
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if cerr := ctx.Err(); cerr != nil {
			return cerr
		}
		if d.IsDir() {
			return nil
		}
		fi, err := d.Info()
		if err != nil {
			return nil
		}
		total += fi.Size()
		return nil
	})
	return total, err
}

// TruncateFileIfOver writes empty content when size exceeds maxBytes.
// maxBytes <= 0 disables truncation.
func TruncateFileIfOver(path string, maxBytes int64) (truncated bool, before int64, err error) {
	if maxBytes <= 0 {
		return false, 0, nil
	}
	fi, err := os.Stat(path)
	if err != nil {
		return false, 0, err
	}
	if fi.IsDir() {
		return false, 0, nil
	}
	before = fi.Size()
	if before <= maxBytes {
		return false, before, nil
	}
	if err := os.Truncate(path, 0); err != nil {
		return false, before, err
	}
	return true, before, nil
}
